Fe refactor payment
hatchways/team-cosmic-crisp pull request #81
Opened 2021-06-07 10:24 UTC by xia0m

### What this PR does (required):
- refactor payment

### Screenshots / Videos (required):

https://user-images.githubusercontent.com/6465981/121000830-84370f00-c73f-11eb-8b7a-55423ff120f6.mp4

### Any information needed to test this feature (required):
- use sitter@email.com, 123456 for dog sitter,
- use owner@email.com, 123456 for dog owner
- go to listing page, find Sitter Dog, and create a new request
- on sitter's panel, go to request page, the new request should be there
- click the vertical three dot to accept/decline the request
- if accept, owner is able to pay for the dog sitting.

### Any issues with the current functionality (optional):

2021-06-09 16:13 UTC, rajivtitus commented on client/src/App.tsx
> +                  <Route exact path="/requests" component={Request} />
Please make this a protected route, although users who are not logged in won't be able to see any data but we wouldn't want them navigating to this page.

2021-06-09 16:17 UTC, rajivtitus commented on client/src/components/Navbar/Navbar.tsx
> +        <Link to="/requests" className={classes.link}>
You can merge Link and Button. 
Eg: "<Button component={Link} to='/requests'>Request</Button>"

2021-06-09 16:40 UTC, rajivtitus commented on client/src/components/ProfileDetails/RequestForm/RequestForm.tsx
>        postRequest(sitter._id, startDate, endDate).then((data) => {
Data is being defined but never used, please exclude 'data' and address warning.

2021-06-09 17:05 UTC, rajivtitus requested changes

2021-06-09 17:05 UTC, rajivtitus commented on client/src/pages/Checkout/Checkout.tsx
>  export default function Order(): JSX.Element {
Once we are on Checkout page, please make Drop-In/Drop-Off dates and times read-only or maybe include the data in a Typography, as we wouldn't want users to change these details after sitter has confirmed the booking request.

Note: You can either work on this or create a new issue and assign it to one of us :)

2021-06-09 17:05 UTC, rajivtitus commented on client/src/components/Navbar/Navbar.tsx
>        <Link to="/bookings" className={classes.link}>
Ditto here!

You can merge Link and Button.
Eg: `<Button component={Link} to='/requests'>Request</Button>`

2021-06-09 17:52 UTC, gursharan4312 commented
Couple of things:
- Change request id when it's passed to Payment component as it is hardcoded as of now
- You can add payment date and time in the request table when user has paid to confirm user that he has paid
- Please make a model or redirect to requests page when payment is successful.

2021-06-11 04:02 UTC, gursharan4312 approved these changes

2021-06-11 04:31 UTC, merged